export type DomainErrorCode =
  | 'IDENTITY_ALREADY_LINKED'
  | 'INTERNAL_TRANSFER_OPT_IN_REQUIRED'
  | 'INVALID_SOLANA_ADDRESS'
  | 'INVALID_TRANSFER_AMOUNT'
  | 'RECIPIENT_NOT_FOUND'
  | 'SELF_TRANSFER_NOT_ALLOWED'
  | 'SENDER_WALLET_NOT_FOUND'
  | 'WALLET_ADDRESS_ALREADY_BOUND'
  | 'WALLET_PROOF_INVALID'
  | 'PAIRING_CODE_TARGET_PLATFORM_MISMATCH'
  | 'PAIRING_TARGET_PLATFORM_MUST_DIFFER'
  | 'PAIRING_CODE_EXPIRED'
  | 'PAIRING_CODE_INVALID'
  | 'PAIRING_CODE_REPLAYED'
  | 'PAIRING_REQUEST_EXPIRED'
  | 'PAIRING_REQUEST_INVALID'
  | 'PAIRING_REQUEST_NOT_AUTHORIZED'
  | 'PAIRING_SOURCE_NOT_FOUND'
  | 'TARGET_IDENTITY_ALREADY_LINKED'
  | 'VALIDATION_ERROR'

export class DomainError extends Error {
  public readonly code: DomainErrorCode

  public constructor(code: DomainErrorCode, message: string) {
    super(message)
    this.name = 'DomainError'
    this.code = code
  }
}
